Repository appwex/react-ui-components, pull requests merged in 2022-12, with the labels that each got.

#9 Add Code and Contribute Guidelines
  README.md
  docs/Code_Contribute_Guidelines.md
  src/App.js
Labels: documentation, ready for review

#14 Add Stories Component
  docs/Story_Usage.md
  src/App.css
  src/App.jsx
  src/components/footer/footer.css
  src/components/footer/footer.jsx
  src/components/header/header.css
  src/components/header/header.jsx
  src/index.js
  src/routes/a-components/Component.css
  src/routes/a-components/Component.jsx
  src/routes/error-page/error-page.jsx
  src/routes/homepage/homepage.jsx
  src/routes/stories/Stories.css
  src/routes/stories/Stories.jsx
  src/routes/stories/index.jsx
  src/routes/story-page/componet.jsx
  src/routes/story-page/story-page.css
  src/routes/story-page/story-page.jsx
  src/routes/test-page.jsx/test-page.jsx
Labels: ready for review

#17 Ruc/rana/15
  src/index.js
  src/routes/button/Button.css
  src/routes/button/Button.jsx
  src/routes/button/index.jsx
  src/routes/story-page/button.jsx
  src/routes/story-page/story-page.jsx
Labels: ready for review

#23 Eslint and other minor fix
  .eslintrc
  src/components/notifications/notificationBar.css
  src/components/notifications/notificationBar.jsx
  src/components/notifications/notifications.css
  src/components/notifications/notifications.jsx
  src/index.js
  src/routes/button/Button.jsx
  src/routes/button/index.jsx
  src/routes/story-page/button.jsx
Labels: ready for review

#26 Add Notification-Bar Component
  .prettierrc
  src/assets/svg/congratulation.svg
  src/assets/svg/notification-error.svg
  src/assets/svg/receive.svg
  src/assets/svg/send.svg
  src/assets/svg/setting.svg
  src/components/notifications/notificationBar.css
  src/components/notifications/notificationBar.jsx
  src/components/notifications/notifications.css
  src/components/notifications/notifications.jsx
  src/index.css
  src/index.js
  src/routes/notification-page/index.jsx
  src/routes/story-page/story-page.jsx
Labels: UI, ready for review

#35 Add payment review box component
  src/App.jsx
  src/index.js
  src/routes/payment/payment.css
  src/routes/payment/payment.jsx
  src/routes/story-page/story-page.jsx
Labels: ready for review

#41 first commit cookie component
  src/assets/svg/christmas-cookie.svg
  src/index.js
  src/routes/cookie/cookie.css
  src/routes/cookie/cookie.jsx
  src/routes/payment/payment.jsx
  src/routes/story-page/story-page.jsx
Labels: in progress, ready for review

#45 Add Chart Component for #20
  src/assets/svg/collapsed.svg
  src/assets/svg/positive.svg
  src/components/chart/chart.css
  src/components/chart/chart.jsx
  src/index.css
  src/index.js
  src/routes/chart-page/chart-page.css
  src/routes/chart-page/index.jsx
  src/routes/story-page/story-page.jsx
Labels: UI, ready for review

#47 add recent activites component
  src/index.js
  src/routes/recent-activities/recent-activities.css
  src/routes/recent-activities/recent-activities.jsx
  src/routes/story-page/story-page.jsx
Labels: in progress, ready for review

#54 Profile-Component
  package-lock.json
  src/assets/images/avatar.png
  src/index.js
  src/routes/profile/profile.css
  src/routes/profile/profile.jsx
  src/routes/story-page/story-page.jsx
Labels: ready for review

#57 ruc/nadiafr/another profile
  src/assets/svg/edit-icon.svg
  src/assets/svg/profileImg.svg
  src/components/anotherProfile/anotherProfile.css
  src/components/anotherProfile/anotherProfile.jsx
  src/index.js
  src/routes/story-page/story-page.jsx
Labels: in progress, ready for review

#61 coins Value component
  src/assets/svg/bitcoin.svg
  src/assets/svg/bnb.svg
  src/assets/svg/etherium.svg
  src/index.js
  src/routes/coin-value/coinValue.css
  src/routes/coin-value/coinValue.jsx
  src/routes/story-page/story-page.jsx
Labels: ready for review

#62 add information component
  src/assets/svg/profile-icon.svg
  src/assets/svg/tick-icon.svg
  src/index.js
  src/routes/add-information/add-information.css
  src/routes/add-information/add-information.jsx
  src/routes/story-page/story-page.jsx
Labels: in progress, ready for review

#63 referral component
  src/assets/images/code-barre.png
  src/index.js
  src/routes/referral/referral.css
  src/routes/referral/referral.jsx
  src/routes/story-page/story-page.jsx
Labels: in progress, ready for review

#65 update page and navigation fix
  src/index.js
  src/routes/story-page/story-page.css
Labels: enhancement, ready for review

#71 Ruc/demandtech/button with multiple type
  src/assets/svg/btn-loading.svg
  src/index.js
  src/routes/button/Button.css
  src/routes/button/Button.jsx
  src/routes/button/index.jsx
  src/routes/buttons/buttons.css
  src/routes/buttons/buttons.jsx
  src/routes/profile/profile.jsx
  src/routes/story-page/button.jsx
  src/routes/story-page/story-page.jsx
Labels: in progress

#69 ADD GRAPH COMPONENT
  package-lock.json
  package.json
  src/index.js
  src/routes/graph-component/customToolTip.jsx
  src/routes/graph-component/graph.css
  src/routes/graph-component/graph.jsx
  src/routes/story-page/story-page.jsx
Labels: UI, ready for review
